# 동엽
#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/test
#    username: root
#    password: root
#    driver-class-name: org.mariadb.jdbc.Driver
#
#  # JPA 기본 설정, 운영 시 update 나 none 설정
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
#        format_sql: true
#        show_sql: true
#
#  jooq:
#    sql: org.jooq.meta.mariadb.MariaDBDatabase
#    schema-name: test
#
#logging:
#  level:
#    org.hibernate.SQL: WARN  # 실행된 SQL 쿼리를 디버깅 로그로 확인
#    org.hibernate.type.descriptor.sql: WARN  # hibernate 에서 SQL 파라미터 바인딩 로깅


# 광연
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/danjitalk
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 기본 설정, 운영 시 update 나 none 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jooq:
    sql: org.jooq.meta.mysql.MySQLDatabase
    schema-name: danjitalk

logging:
  level:
    org.hibernate.SQL: info  # 실행된 SQL 쿼리를 디버깅 로그로 확인
    org.hibernate.type.descriptor.sql: info  # hibernate 에서 SQL 파라미터 바인딩 로깅
