spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA 기본 설정, 운영 시 update 나 none 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true
logging:
  level:
    org.hibernate.SQL: WARN  # 실행된 SQL 쿼리를 디버깅 로그로 확인
    org.hibernate.type.descriptor.sql: WARN  # hibernate 에서 SQL 파라미터 바인딩 로깅
