spring:
  datasource:
    url: #
    username: #
    password: #
    driver-class-name: #

  # JPA 기본 설정, 운영 시 update 나 none 설정
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false
        show_sql: false

logging:
  level:
    root: WARN