server:
  port: 8080

spring:
  profiles:
    active: dev   # 기본 설정, 추후 배포시 환경변수로 변경 가능
  datasource:
    hikari:
      maximum-pool-size: 50 # HikariCP 연결 풀 크기 설정

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

# TRACE(상세) > DEBUG(디버깅) > INFO(정보) > WARN(경고) > ERROR(에러) > FATAL(치명적 에러) > OFF(끄기)
logging:
  level:
    root: INFO  # 기본 로그 레벨
    org.springframework: INFO

aws:
  s3:
    region: ${AWS_REGION:ap-northeast-2}
    access-key: ${AWS_ACCESS_KEY:test}
    secret-key: ${AWS_SECRET_ACCESS_KEY:test}
    bucket-name: ${AWS_BUCKET_NAME:test}

jwt:
  secret:
    access: ${ACCESS_SECRET}
    refresh: ${REFRESH_SECRET}